import '../data_model/meal_item.dart';
import '../data_model/restaurant_item.dart';

final String _restaurantDescription =
"""Short description, 280 character limit, describing the meal and all the 
ingredients involved. Opportunity to convey a message to customers 
and sell the product""";

RestaurantItemList tempRestaurantList = RestaurantItemList(restaurantItems: [
  RestaurantItem(
    id: 1,
    headerImage: 'images/Chicken.jfif',
    logoImage: 'images/Logo.png',
    name: "Mr. Roberts",
    description: _restaurantDescription,
    estimatedDeliveryTime: 30,
    deliveryFee: 1,
    restaurantMenu: <MealItem>[
      MealItem(
          id: 1,
          name: "Beef Burger",
          restaurantName: "BBQ City",
          basePrice: 15.00,
          image: 'images/Burger.jpg',
          description: _restaurantDescription,
          estDeliveryTime: 35,
          deliveryFee: 1),
      MealItem(
          id: 2,
          name: "Gretaben",
          restaurantName: "PizzaMan",
          basePrice: 45.00,
          image: 'images/Noodles.jpg',
          description: _restaurantDescription,
          estDeliveryTime: 30,
          deliveryFee: 2),
    ],
  ),
  RestaurantItem(
    id: 2,
    headerImage: 'images/Burger.jpg',
    logoImage: 'images/Logo.png',
    name: "BBQ City",
    description: _restaurantDescription,
    estimatedDeliveryTime: 30,
    deliveryFee: 1,
    restaurantMenu: <MealItem>[
      MealItem(
        id: 7,
        name: "Fried Chicken & Yam Chips",
        restaurantName: "Mr. Roberts",
        basePrice: 12.00,
        image: 'images/Chicken.jfif',
        description: _restaurantDescription,),
      MealItem(
        id: 8,
        name: "Pork & Fried Yam",
        restaurantName: "Acuzzi",
        basePrice: 8.00,
        image: 'images/Rice.jpg',
        description: _restaurantDescription,),
      MealItem(
          id: 1,
          name: "Beef Burger",
          restaurantName: "BBQ City",
          basePrice: 15.00,
          image: 'images/Burger.jpg',
          description: _restaurantDescription,
          estDeliveryTime: 35,
          deliveryFee: 1),
      MealItem(
          id: 2,
          name: "Gretaben",
          restaurantName: "PizzaMan",
          basePrice: 45.00,
          image: 'images/Noodles.jpg',
          description: _restaurantDescription,
          estDeliveryTime: 30,
          deliveryFee: 2),
    ],
  ),
  RestaurantItem(
    id: 3,
    headerImage: 'images/Noodles.jpg',
    logoImage: 'images/Logo.png',
    name: "Didi",
    description: _restaurantDescription,
    estimatedDeliveryTime: 20,
    deliveryFee: 2,
    restaurantMenu: <MealItem>[
      MealItem(
          id: 1,
          name: "Beef Burger",
          restaurantName: "BBQ City",
          basePrice: 15.00,
          image: 'images/Burger.jpg',
          description: _restaurantDescription,
          estDeliveryTime: 35,
          deliveryFee: 1),
      MealItem(
          id: 2,
          name: "Gretaben",
          restaurantName: "PizzaMan",
          basePrice: 45.00,
          image: 'images/Noodles.jpg',
          description: _restaurantDescription,
          estDeliveryTime: 30,
          deliveryFee: 2),
    ],
  ),
  RestaurantItem(
    id: 4,
    headerImage: 'images/Rice.jpg',
    logoImage: 'images/Logo.png',
    name: "Brunei Cafeteria",
    description: _restaurantDescription,
    estimatedDeliveryTime: 15,
    deliveryFee: 3,
    restaurantMenu: <MealItem>[
      MealItem(
        id: 7,
        name: "Fried Chicken & Yam Chips",
        restaurantName: "Mr. Roberts",
        basePrice: 12.00,
        image: 'images/Chicken.jfif',
        description: _restaurantDescription,),
      MealItem(
        id: 8,
        name: "Pork & Fried Yam",
        restaurantName: "Acuzzi",
        basePrice: 8.00,
        image: 'images/Rice.jpg',
        description: _restaurantDescription,),
    ],
  ),
  RestaurantItem(
    id: 5,
    headerImage: 'images/Local.jpg',
    logoImage: 'images/Logo.png',
    name: "Sanbra",
    description: _restaurantDescription,
    estimatedDeliveryTime: 30,
    deliveryFee: 1,
    restaurantMenu: <MealItem>[
      MealItem(
        id: 7,
        name: "Fried Chicken & Yam Chips",
        restaurantName: "Mr. Roberts",
        basePrice: 12.00,
        image: 'images/Chicken.jfif',
        description: _restaurantDescription,),
      MealItem(
        id: 8,
        name: "Pork & Fried Yam",
        restaurantName: "Acuzzi",
        basePrice: 8.00,
        image: 'images/Rice.jpg',
        description: _restaurantDescription,),
      MealItem(
          id: 1,
          name: "Beef Burger",
          restaurantName: "BBQ City",
          basePrice: 15.00,
          image: 'images/Burger.jpg',
          description: _restaurantDescription,
          estDeliveryTime: 35,
          deliveryFee: 1),
      MealItem(
          id: 2,
          name: "Gretaben",
          restaurantName: "PizzaMan",
          basePrice: 45.00,
          image: 'images/Noodles.jpg',
          description: _restaurantDescription,
          estDeliveryTime: 30,
          deliveryFee: 2),
    ],
  ),
]);