import '../data_model/meal_item.dart';
import '../data_model/restaurant_item.dart';

final String _restaurantDescription =
"""Short description, 280 character limit, describing the meal and all the 
ingredients involved. Opportunity to convey a message to customers 
and sell the product""";

RestaurantItemList tempRestaurantList = RestaurantItemList(restaurantItems: [
  RestaurantItem(
    id: 1,
    restaurantHeaderImage: 'images/Chicken.jfif',
    restaurantLogo: 'images/Logo.png',
    restaurantName: "Mr. Roberts",
    restaurantDescription: _restaurantDescription,
    estimatedDeliveryTime: 30,
    deliveryFee: 1,
    restaurantMenu: <MealItem>[
      MealItem(
          id: 1,
          mealName: "Beef Burger",
          restaurantName: "BBQ City",
          mealBasePrice: 15.00,
          mealImage: 'images/Burger.jpg',
          mealDescription: _restaurantDescription,
          estimatedDeliveryTime: 35,
          deliveryFee: 1),
      MealItem(
          id: 2,
          mealName: "Gretaben",
          restaurantName: "PizzaMan",
          mealBasePrice: 45.00,
          mealImage: 'images/Noodles.jpg',
          mealDescription: _restaurantDescription,
          estimatedDeliveryTime: 30,
          deliveryFee: 2),
    ],
  ),
  RestaurantItem(
    id: 2,
    restaurantHeaderImage: 'images/Burger.jpg',
    restaurantLogo: 'images/Logo.png',
    restaurantName: "BBQ City",
    restaurantDescription: _restaurantDescription,
    estimatedDeliveryTime: 30,
    deliveryFee: 1,
    restaurantMenu: <MealItem>[
      MealItem(
        id: 7,
        mealName: "Fried Chicken & Yam Chips",
        restaurantName: "Mr. Roberts",
        mealBasePrice: 12.00,
        mealImage: 'images/Chicken.jfif',
        mealDescription: _restaurantDescription,),
      MealItem(
        id: 8,
        mealName: "Pork & Fried Yam",
        restaurantName: "Acuzzi",
        mealBasePrice: 8.00,
        mealImage: 'images/Rice.jpg',
        mealDescription: _restaurantDescription,),
      MealItem(
          id: 1,
          mealName: "Beef Burger",
          restaurantName: "BBQ City",
          mealBasePrice: 15.00,
          mealImage: 'images/Burger.jpg',
          mealDescription: _restaurantDescription,
          estimatedDeliveryTime: 35,
          deliveryFee: 1),
      MealItem(
          id: 2,
          mealName: "Gretaben",
          restaurantName: "PizzaMan",
          mealBasePrice: 45.00,
          mealImage: 'images/Noodles.jpg',
          mealDescription: _restaurantDescription,
          estimatedDeliveryTime: 30,
          deliveryFee: 2),
    ],
  ),
  RestaurantItem(
    id: 3,
    restaurantHeaderImage: 'images/Noodles.jpg',
    restaurantLogo: 'images/Logo.png',
    restaurantName: "Didi",
    restaurantDescription: _restaurantDescription,
    estimatedDeliveryTime: 20,
    deliveryFee: 2,
    restaurantMenu: <MealItem>[
      MealItem(
          id: 1,
          mealName: "Beef Burger",
          restaurantName: "BBQ City",
          mealBasePrice: 15.00,
          mealImage: 'images/Burger.jpg',
          mealDescription: _restaurantDescription,
          estimatedDeliveryTime: 35,
          deliveryFee: 1),
      MealItem(
          id: 2,
          mealName: "Gretaben",
          restaurantName: "PizzaMan",
          mealBasePrice: 45.00,
          mealImage: 'images/Noodles.jpg',
          mealDescription: _restaurantDescription,
          estimatedDeliveryTime: 30,
          deliveryFee: 2),
    ],
  ),
  RestaurantItem(
    id: 4,
    restaurantHeaderImage: 'images/Rice.jpg',
    restaurantLogo: 'images/Logo.png',
    restaurantName: "Brunei Cafeteria",
    restaurantDescription: _restaurantDescription,
    estimatedDeliveryTime: 15,
    deliveryFee: 3,
    restaurantMenu: <MealItem>[
      MealItem(
        id: 7,
        mealName: "Fried Chicken & Yam Chips",
        restaurantName: "Mr. Roberts",
        mealBasePrice: 12.00,
        mealImage: 'images/Chicken.jfif',
        mealDescription: _restaurantDescription,),
      MealItem(
        id: 8,
        mealName: "Pork & Fried Yam",
        restaurantName: "Acuzzi",
        mealBasePrice: 8.00,
        mealImage: 'images/Rice.jpg',
        mealDescription: _restaurantDescription,),
    ],
  ),
  RestaurantItem(
    id: 5,
    restaurantHeaderImage: 'images/Local.jpg',
    restaurantLogo: 'images/Logo.png',
    restaurantName: "Sanbra",
    restaurantDescription: _restaurantDescription,
    estimatedDeliveryTime: 30,
    deliveryFee: 1,
    restaurantMenu: <MealItem>[
      MealItem(
        id: 7,
        mealName: "Fried Chicken & Yam Chips",
        restaurantName: "Mr. Roberts",
        mealBasePrice: 12.00,
        mealImage: 'images/Chicken.jfif',
        mealDescription: _restaurantDescription,),
      MealItem(
        id: 8,
        mealName: "Pork & Fried Yam",
        restaurantName: "Acuzzi",
        mealBasePrice: 8.00,
        mealImage: 'images/Rice.jpg',
        mealDescription: _restaurantDescription,),
      MealItem(
          id: 1,
          mealName: "Beef Burger",
          restaurantName: "BBQ City",
          mealBasePrice: 15.00,
          mealImage: 'images/Burger.jpg',
          mealDescription: _restaurantDescription,
          estimatedDeliveryTime: 35,
          deliveryFee: 1),
      MealItem(
          id: 2,
          mealName: "Gretaben",
          restaurantName: "PizzaMan",
          mealBasePrice: 45.00,
          mealImage: 'images/Noodles.jpg',
          mealDescription: _restaurantDescription,
          estimatedDeliveryTime: 30,
          deliveryFee: 2),
    ],
  ),
]);